### PR TITLE
Fix compatibility with core 2.231

### PR DESCRIPTION
**Pull request by timja**
https://github.com/jenkinsci/jenkins/pull/4604 removed jsr305 dependency from the core war, we have a feature where we check for certain null / non null annotations in the DataBoundConfigurator, https://github.com/jenkinsci/configuration-as-code-plugin/blob/02ca4728571a26465339742f532c9e50fe629b07/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java#L118

Without this fix, it breaks with:

```
jenkins    | 2020-04-15 13:20:19.974+0000 [id=32]    WARNING    jenkins.model.Jenkins$5#runTask: ConfigurationAsCode.init failed perhaps due to plugin dependency issues
jenkins    | java.lang.ClassNotFoundException: javax.annotation.Nonnull
jenkins    |     at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
jenkins    |     at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
jenkins    |     at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
jenkins    |     at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
jenkins    | Caused: java.lang.NoClassDefFoundError: javax/annotation/Nonnull
jenkins    |     at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:118)
jenkins    |     at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:77)
jenkins    |     at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:267)
jenkins    |     at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.check(DataBoundConfigurator.java:101)
jenkins    |     at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:344)
jenkins    |     at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
jenkins    |     at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:352)
jenkins    |     at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:287)
jenkins    |     at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$7(ConfigurationAsCode.java:743)
jenkins    |     at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:693)
jenkins    |     at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:743)
jenkins    |     at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:728)
jenkins    |     at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:608)
jenkins    |     at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:291)
jenkins    |     at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:283)
jenkins    | Caused: java.lang.reflect.InvocationTargetException
jenkins    |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins    |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins    |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins    |     at java.lang.reflect.Method.invoke(Method.java:498)
jenkins    |     at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
jenkins    | Caused: java.lang.Error
jenkins    |     at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
jenkins    |     at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
jenkins    |     at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
jenkins    |     at jenkins.model.Jenkins$5.runTask(Jenkins.java:1132)
jenkins    |     at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
jenkins    |     at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins    |     at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
jenkins    |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins    |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins    |     at java.lang.Thread.run(Thread.java:748)
```

Minimal reproducer:

```
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: my-test-token
              secret: 'a secret'
              description: Secret token
```
(note that much of jcasc does work, many attributes don't use this configurator but credentials is one that does)

also note that I was unable to reproduce this in hpi:run, but I was able to re-produce it in a standalone jenkins instance and verify it's fixed

I found this when testing an upgrade at work, at least I'm the first one to hit it 🤦.

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by jetersen** [comment]
Is their no better way to achieve the same without JSR 305?

**Comment by jtnord** [comment]
> Is their no better way to achieve the same without JSR 305?

check the annotation classname rather than the class itself.  (which is what spotbugs acutally does to support a viarety of `Nonnull` classes.

re-introducing jsr-305 goes against the point of getting rid of it as it has a horrible license.

now the annotation won't be present unless the class can be loaded (and this will cause you not to find the annotations even if you declare it - iff the classloader  of the class with the declaration does not declare the class.  so what you are trying to achieve is probably doomed to failure anyway (or the other plugin will have the class but it will be a different one due to the classloader)

**Comment by timja** [comment]
> > Is their no better way to achieve the same without JSR 305?
> 
> check the annotation classname rather than the class itself. (which is what spotbugs acutally does to support a viarety of `Nonnull` classes.
> 
> re-introducing jsr-305 goes against the point of getting rid of it as it has a horrible license.
> 
> now the annotation won't be present unless the annotation class can be loaded (and this may well cause you not to find the annotations even if you provide it - if the classloader of the class with the use of the annotation can not load the class via itself or its parents. So what you are trying to achieve here is probably doomed to failure anyway (or the other plugin will have the class but it will be a different one due to the classloader and then probably not match when you expect it would - and your unit tests give false positives due to the Classloading differences in Jenkins vs JenkinsRule)

it was tested interactively, couldn't re-produce it via hpi:run

**Comment by jtnord** [comment]
BTW- the [code ](https://github.com/jenkinsci/configuration-as-code-plugin/blob/29a2fe2a91942b13e970e61f404170acfb369d0b/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java#L118-L122) doesn't seem to look for `NonNull` from spotbugs - so you appear to be missing some cases.

**Comment by timja** [comment]
> BTW- the [code ](https://github.com/jenkinsci/configuration-as-code-plugin/blob/29a2fe2a91942b13e970e61f404170acfb369d0b/plugin/src/main/java/io/jenkins/plugins/casc/impl/configurators/DataBoundConfigurator.java#L118-L122) doesn't seem to look for `NonNull` from spotbugs - so you appear to be missing some cases.

http://findbugs.sourceforge.net/api/edu/umd/cs/findbugs/annotations/NonNull.html
retension isn't set to runtime

**Comment by timja** [comment]
@jetersen @jtnord I've raised https://github.com/jenkinsci/configuration-as-code-plugin/issues/1360

feel free to continue any discussion there, it's up for grabs if anyone wants to take it, I don't have time right now

**Pull request merged**
