### PR TITLE
fix: The credentials id is a array rather than name

### PR DESCRIPTION
**Pull request by nabeelraja**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by timja** [comment]
What makes you think that? The tests are showing that it's not right at least in the version we are testing against

**Comment by nabeelraja** [comment]
> What makes you think that? The tests are showing that it's not right at least in the version we are testing against

We were using this documentation to configure sonar config as code in charts, however our deployments were failing. Then we did revers engineering by manually saving the Sonar config via the Jenkins console and then extracted the output via Jenkins as Code Configurator. On comparing the output with the given documentation we identified that the credentialsid was marked as an array rather than the name. After correcting the format we were able to successfully deploy the helms chart.
Jenkins Version: 2.365 (LTS)

**Comment by timja** [comment]
This isn't right as far as I can tell.

Here's an example from the latest weekly version and latest sonar plugin:
https://github.com/hmcts/cnp-flux-config/blob/master/apps/jenkins/jenkins/jenkins.yaml#L160-L166

**Comment by nabeelraja** [comment]
image

**Comment by timja** [comment]
that's the same as what I posted it's not credentials Id that's an array it's the installation, you can have the fields in any order in yaml. check your yaml closer from what you've changed here vs the export.

**Pull request closed without merging**
