### PR TITLE
Integrate security fix from 1.55.1

### PR DESCRIPTION
**Pull request by Wadeck**
⚠️ This PR should be merged using merge-commit, not using squash-commit or rebase-commit, to ensure the commits related to the release are on the history of the default branch.

💡 Feel free to amend this PR to go back to 1.56 if you want.

### CODE REVIEW

**Comment by jetersen** [comment]
Again this repo uses squash and merge usually so another change to suit. I would prefer we use rebase in this case or that commits are pushed directly to master.

**Comment by daniel-beck** [comment]
Another option would be to cherry-pick only the fix commit into master, basically as if 1.55.1 was a backport unrelated to master.

**Comment by jetersen** [comment]
@daniel-beck that seems like a better solution.

**Comment by daniel-beck** [comment]
@jetersen Do you want a PR with that commit, or is that something you'd do on the git CLI?

**Comment by jetersen** [comment]
it is just `git cherry-pick 4f42567`? or do we want to special flags on the cherry-pick?

**Comment by daniel-beck** [comment]
You could set `-x` if you want to be have a reference into this branch (similar to how we cherry-pick LTS backports into core), but really up to your preference.

**Comment by jetersen** [comment]
WDYT @timja

**Comment by timja** [comment]
Sounds good to me

**Comment by jetersen** [comment]
Whatever, merge request it will be, though I have to change repository settings 😓 Than we would switch to automated releases I think 👍

**Pull request merged**
