### PR TITLE
Remove matrix-auth from support plugin

### PR DESCRIPTION
**Pull request by daniel-beck**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!

- [x] Please describe what you did

- [ ] Link to relevant GitHub issues or pull requests

- [ ] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org)

- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### Description

Adapt to https://github.com/jenkinsci/matrix-auth-plugin/pull/48

### CODE REVIEW

**Comment by casz** [comment]
Now with [wip app](https://github.com/wip/app) no one can accidentally merge it :)

**Comment by timja** [comment]
@casz @daniel-beck we ready to remove support in jcasc now that matrix-auth has been released?

**Comment by timja** [comment]
🚢 ?

**Comment by casz** [comment]
We should update the docs to say we require matrix auth plugin 2.4

**Comment by timja** [comment]
done

**Pull request merged**
