### PR TITLE
warning on export feature

### PR DESCRIPTION
**Pull request by ndeloof**
capture d ecran 2018-09-12 a 10 24 44

### CODE REVIEW

**Comment by ewelinawilkosz** [comment]
looking good, will just wait for CI to finish

**Comment by ewelinawilkosz** [comment]
I agree with @oleg-nenashev and I'd love to do that :) it's just features first, and then the beauty will follow

**Comment by ndeloof** [comment]
I'd be happy some talented web designer help us improve this web page. Unfortunately Jenkins web framework doesn't come with any assistance for it and we mostly get web 1.0 without significant effort.

**Comment by ewelinawilkosz** [comment]
CI failing the usual way, works on my machine though!

**Comment by ndeloof** [comment]
> CI failing the usual way, works on my machine though!
considering we are the Jenkins Community, this is a terrible quote

**Pull request merged**
