### PR TITLE
Fix `mvn test` and move snakeyaml to another repo

### PR DESCRIPTION
**Pull request by timja**
Requires: https://github.com/jenkinsci/plugin-pom/pull/258, https://github.com/timja/configuration-as-code-snakeyaml-lib/pull/1

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Why do we need a separate lib? If you want it to be accepted to Jenkins, I believe it has to be an API plugin then (with a shaded lib inside to avoid conflicts with direct usages)

**Comment by timja** [comment]
> Why do we need a separate lib? If you want it to be accepted to Jenkins, I believe it has to be an API plugin then (with a shaded lib inside to avoid conflicts with direct usages)

Shading it as an api plugin doesn't seem to work, looks to be because of:
https://issues.jenkins-ci.org/browse/JENKINS-28796

`mvn test` doesn't seem to resolve the dependency on the project and you get compilation failures:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project configuration-as-code: Compilation failure: Compilation failure:
[ERROR] /Users/timja/projects/jenkinsci/configuration-as-code-plugin/plugin/src/test/java/io/jenkins/plugins/casc/misc/Util.java:[11,47] package io.jenkins.plugins.casc.snakeyaml.nodes does not exist
[ERROR] /Users/timja/projects/jenkinsci/configuration-as-code-plugin/plugin/src/test/java/io/jenkins/plugins/casc/yaml/ExportTest.java:[10,47] package io.jenkins.plugins.casc.snakeyaml.error does not exist
```

see the gitter chat for more details

**Comment by oleg-nenashev** [comment]
@timja https://github.com/jenkinsci/docker-traceability-plugin for example of shading a lib inside a plugin. It is not fancy at all (multi-module), but it works

**Comment by timja** [comment]
> @timja [jenkinsci/docker-traceability-plugin](https://github.com/jenkinsci/docker-traceability-plugin) for example of shading a lib inside a plugin. It is not fancy at all (multi-module), but it works

that has packaging `jar`
https://github.com/jenkinsci/docker-traceability-plugin/blob/master/docker-java-shaded/pom.xml#L10

Isn't it the same as what we had before?

**Comment by oleg-nenashev** [comment]
> Isn't it the same as what we had before?

Kinda. But you could reimplement it in a new API plugin. So the API plugin would take care of shading and would not require re-release each time

**Comment by timja** [comment]
> > Isn't it the same as what we had before?
> 
> Kinda. But you could reimplement it in a new API plugin. So the API plugin would take care of shading and would not require re-release each time

I tried to do that but it didn't work, I guess you could make it a multi-module project, with a packaging jar, can try that later on

**Comment by oleg-nenashev** [comment]
> I tried to do that but it didn't work, I guess you could make it a multi-module project, with a packaging jar, can try that later on

That;s why I linked the example

**Comment by timja** [comment]
That plugin doesn't even compile anymore on  java 8 /  recent maven
```
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.3:findbugs (findbugs) on project docker-traceability-parent: Unable to parse configuration of mojo org.codehaus.mojo:findbugs-maven-plugin:3.0.3:findbugs for parameter pluginArtifacts: Cannot assign configuration entry 'pluginArtifacts' with value '${plugin.artifacts}' of type java.util.Collections.UnmodifiableRandomAccessList to property of type java.util.ArrayList -> [Help 1]
[ERROR]
```

**Comment by timja** [comment]
I've made it work now, see 
https://github.com/timja/configuration-as-code-snakeyaml-plugin/pull/1

https://github.com/jenkinsci/configuration-as-code-plugin/pull/1205/commits/ba6e54c3ae6fa773ddef61b6fafbd0998585f4cc
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1205/commits/9b95c8b4347022c2d675d1a098ccd1adf6f57e8a

**Comment by casz** [comment]
@timja do we want to move forward with this or can we close it?

**Comment by timja** [comment]
close for now, will re-visit

**Pull request closed without merging**
