### PR TITLE
chore: Bump integration Jenkins version to 2.346.3

### PR DESCRIPTION
**Pull request by NotMyFault**

### CODE REVIEW

**Comment by jetersen** [comment]
Perhaps we could introduce updatecli here to avoid these workflows? 🤔
Or is it because your testing against a newer version to see if it passes?

**Comment by NotMyFault** [comment]
> Perhaps we could introduce updatecli here to avoid these workflows? 🤔

That would be nice, at least for point releases.

> Or is it because your testing against a newer version to see if it passes?

No, this is intended to be merged. It's the next point release.

**Comment by jetersen** [comment]
Do you mind if we close this than?
I'll prepare updatecli later tonight.

**Comment by NotMyFault** [comment]
> I'll prepare updatecli later tonight.

Awesome! But I'd like to keep the PR open, at least until all tests pass. Let's turn it into a draft.

**Comment by timja** [comment]
> Perhaps we could introduce updatecli here to avoid these workflows? 🤔 Or is it because your testing against a newer version to see if it passes?

yes would be good, it should be latest LTS, except when we're testing against a new LTS line that's not released yet and it's using the weekly

**Comment by jetersen** [comment]
@timja I will capture that in powershell since I can use it to compare versions of which ever is greater 😅

**Comment by NotMyFault** [comment]
Tests are green, feel free to close this PR at anytime 🎉

**Comment by jetersen** [comment]
@NotMyFault Thanks for contribution closing this, so it is easier to validate that updatecli will do the right thing 👏

**Pull request closed without merging**
