### PR TITLE
The download path for the plugin is computed incorrectly.

### PR DESCRIPTION
**Pull request by MadsNielsen**
There is a missing '/' between the version I.E the download url would become 'http://my.update.site/jenkins/download/plugins/kubernetes/1.10.1kubernetes.hpi' instead of 'http://my.update.site/jenkins/download/plugins/kubernetes/1.10.1/kubernetes.hpi' which is correct.

A typical off-by-one error :)

### CODE REVIEW

**Comment by ndeloof** [comment]
Nice catch. Hopefully plugins metadata could land in update center soon, so we won't need this hack anymore

**Comment by MadsNielsen** [comment]
@ndeloof Credit goes to @JKrag for discovering this

**Comment by JKrag** [comment]
@MadsNielsen Thanks for the shout-out ;-)

and thanks for the super quick fix. Now I am even more impatient for a new alpha ;-)

**Comment by casz** [comment]
@JKrag you can always grab the incrementals from plugin.txt 👍

**Pull request merged**
