### PR TITLE
🚧 hello github action ci are you there?

### PR DESCRIPTION
**Pull request by casz**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by casz** [comment]
Sent a support request to github 😖

**Comment by oleg-nenashev** [comment]
Yes, a new commit is needed to get the Workflow running.
It does not autodetect workflows which existed before the beta access was enabled.
Just push some documentation to YAML

**Comment by timja** [comment]
@casz I re-enabled github actions on the repo, and it's working all the build is failing, see:
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1082/checks?check_run_id=240525081

**Comment by casz** [comment]
@timja related to https://github.com/actions/setup-java/issues/23

**Comment by timja** [comment]
Actions are passing, see:
#1084

**Pull request closed without merging**
