### PR TITLE
#253 - failing testcase for reapplying GlobalJobDslSecurityConfiguration after restart

### PR DESCRIPTION
**Pull request by hawky-4s-**
Failing testcase for #253

### CODE REVIEW

**Comment by casz** [comment]
The diff looks off, did you change line endings?

**Comment by ewelinawilkosz** [comment]
happy to merge once checks are green, anyone knows easier way to retrigger than pushing new commit?

**Comment by casz** [comment]
@ewelinawilkosz close and reopen PR should do it 👍

**Comment by ewelinawilkosz** [comment]
hmm... either I did it too fast, or it's not enough

**Comment by ndeloof** [comment]
cherry-picked by https://github.com/jenkinsci/configuration-as-code-plugin/commit/4dcecb96e4fc036fe1e8558379c574650c167702

**Pull request closed without merging**
