### PR TITLE
Fix issues on switch branches due to jpi files

### PR DESCRIPTION
**Pull request by imonteroperez**
### Highlights
- Before this PR when I try to switch to another branch/tag on `ubuntu:xenial` I'm getting the following error:
```
+ git diff
[...]
warning: CRLF will be replaced by LF in integrations/src/test/resources/plugins/branch-api.jpi.
The file will have its original line endings in your working directory.
[...]
diff --git a/integrations/src/test/resources/plugins/branch-api.jpi b/integrations/src/test/resources/plugins/branch-api.jpi
index b4323d6..01e863d 100644
Binary files a/integrations/src/test/resources/plugins/branch-api.jpi and b/integrations/src/test/resources/plugins/branch-api.jpi differ
[...]
+ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   images/CasC_new-03.png
	modified:   images/reference.png
	modified:   images/sample_form.png
	modified:   images/unclassified.png
	modified:   integrations/src/test/resources/plugins/branch-api.jpi
	modified:   integrations/src/test/resources/plugins/cloudbees-folder.jpi
	modified:   integrations/src/test/resources/plugins/scm-api.jpi
	modified:   integrations/src/test/resources/plugins/structs.jpi
	modified:   plugin/src/main/webapp/img/logo.eps
	modified:   plugin/src/main/webapp/img/logo.png

no changes added to commit (use "git add" and/or "git commit -a")
+ git checkout configuration-as-code-1.54
error: Your local changes to the following files would be overwritten by checkout:
	integrations/src/test/resources/plugins/branch-api.jpi
	integrations/src/test/resources/plugins/cloudbees-folder.jpi
	integrations/src/test/resources/plugins/scm-api.jpi
	integrations/src/test/resources/plugins/structs.jpi
Please, commit your changes or stash them before you can switch branches.
Aborting
```
- It seems it comes from: https://github.com/jenkinsci/configuration-as-code-plugin/commit/fd9376d5bc424d6e2b874407e3ea7e4591681789
- After this PR: 
```
+ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .gitattributes
	modified:   images/CasC_new-03.png
	modified:   images/reference.png
	modified:   images/sample_form.png
	modified:   images/unclassified.png
	modified:   plugin/src/main/webapp/img/logo.eps
	modified:   plugin/src/main/webapp/img/logo.png

no changes added to commit (use "git add" and/or "git commit -a")
+ git checkout configuration-as-code-1.54
Note: checking out 'configuration-as-code-1.54'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 42e078c... [maven-release-plugin] prepare release configuration-as-code-1.54
M	.gitattributes
M	images/CasC_new-03.png
M	images/reference.png
M	images/sample_form.png
M	images/unclassified.png
M	plugin/src/main/webapp/img/logo.eps
M	plugin/src/main/webapp/img/logo.png
```

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Review by jetersen — APPROVED** [review]

**Comment by batmat** [comment]
@jetersen @timja this little fix removes test failures in PCT runs (at least), if you could consider a release, even some kind of intermediate 1.55.2, that would be nice. Thanks a lot.

**Comment by timja** [comment]
Will switch it to CD tomorrow if no one beats me to it

**Comment by jetersen** [comment]
@timja please do. I recently joined a new company and to do is suddenly growing very fast 😰

**Comment by timja** [comment]
in progress: https://github.com/jenkinsci/configuration-as-code-plugin/pull/1840

**Pull request merged**
