### PR TITLE
ci: Build with Java 17 as well

### PR DESCRIPTION
**Pull request by NotMyFault**
Let's be a bit future proof

Jenkinsfile needs a trusted revision, if GH actions don't suffice. Feel free to cherry pick the commit to a head branch 👍🏻

### CODE REVIEW

**Comment by NotMyFault** [comment]
Conflicts resolved.

**Comment by jetersen** [comment]
@NotMyFault please note GitHub finished faster than ci.j 😅

**Comment by NotMyFault** [comment]
> @NotMyFault please note GitHub finished faster than ci.j 😅

True, the build queue on ci.j is _quite_ occupied today

**Comment by jetersen** [comment]
I see value in having more CI capacity so we are not blocked by queues.

**Review by jetersen — APPROVED** [review]

**Pull request merged**
