### PR TITLE
Update htmlunit to 3.x

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Comment by jglick** [comment]
Need to get into a BOM release ASAP.

**Comment by MarkEWaite** [comment]
A first attempt to release a new version of the BOM was launched about in [build 1772](https://ci.jenkins.io/job/Tools/job/bom/job/master/1772/).  It failed after 4.5 hours with no failures reported in any of the plugin tests.  I've restarted the job as [build 1773](https://ci.jenkins.io/job/Tools/job/bom/job/master/1773/)

**Comment by basil** [comment]
> ASAP

The rush could have been avoided had https://github.com/jenkinsci/jenkins-test-harness/pull/589#event-9425734519 not forestalled my intention to have the migration work completed prior to the merge and release of https://github.com/jenkinsci/jenkins-test-harness/pull/589.

**Pull request merged**
