### PR TITLE
Limit concurrency on workflow

### PR DESCRIPTION
**Pull request by jetersen**
We have too many checks and limitation on the build queue so it gets stuck for hours.

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Review by timja — COMMENTED** [review]
Not sure if this will work won’t it cancel a release too?

**Comment by jetersen** [comment]
Again https://github.com/jenkinsci/configuration-as-code-plugin/actions/workflows/cd.yaml created 55 runs before even getting one release out the door.

**Comment by jetersen** [comment]
We can also entirely remove `on check_run` and have it as workflow dispatch.

**Comment by timja** [comment]
> We can also entirely remove `on check_run` and have it as workflow dispatch.

That may be simplest trivial to hit the button, each action should only take 5 seconds to complete but I assume there's a queue problem that means it doesn't scale.

We could also reduce our github CI down just to running codecov?

**Review by timja — APPROVED** [review]

**Pull request merged**
