### PR TITLE
Chinese localization migration

### PR DESCRIPTION
**Pull request by LinuxSuRen**
see https://github.com/jenkinsci/localization-zh-cn-plugin

### CODE REVIEW

**Comment by casz** [comment]
@LinuxSuRen unsure of the process here, do we wait for you to release the localization plugin before we merge/release this plugin?

**Comment by LinuxSuRen** [comment]
@casz Chinese localization plugin was released. The test result is ok.

**Comment by casz** [comment]
@LinuxSuRen https://github.com/jenkinsci/localization-zh-cn-plugin/commit/1b985e1089d3c449840add7d1d41bc8c3ca5a99b you have an unreleased commit: https://github.com/jenkinsci/localization-zh-cn-plugin/commit/1b985e1089d3c449840add7d1d41bc8c3ca5a99b which was my concern 😅

**Comment by LinuxSuRen** [comment]
@casz Those changes already be released.

**Comment by LinuxSuRen** [comment]
ping @casz

**Pull request merged**
