### PR TITLE
use `VersionConverter` instead of lambda

### PR DESCRIPTION
**Pull request by casz**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!

- [x] Please describe what you did

- [ ] Link to relevant GitHub issues or pull requests

- [ ] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org)

- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### Description

Java complains that target method is generic and cannot compile.
Seems EnumConverter already exist so let's use that.
```java
Stapler.CONVERT_UTILS.register((type, value) -> Version.of(value.toString()), Version.class);
```

### CODE REVIEW

**Comment by casz** [comment]
Well dammit tests fails

**Comment by casz** [comment]
problem is somewhere between 2.60.3 and the latest release of Jenkins the `org.apache.commons.beanutils.Converter#convert` changed signature and no longer accepts lambda because it is an interface.

**Comment by timja** [comment]
is this an issue?

**Comment by casz** [comment]
Yes especially with the new LTS and anything newer than 2.173

**Comment by casz** [comment]
See: https://github.com/jenkinsci/jenkins/pull/3948

**Comment by casz** [comment]
I have no idea how to write this code safe for both versions :sob:

**Comment by timja** [comment]
create a separate class?
remove this functionality 👅 
another way of converting it?

**Pull request merged**
