### PR TITLE
Rename /docs/howToContribute.md to /CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by casz**
As according to https://help.github.com/articles/setting-guidelines-for-repository-contributors/ 👍

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I would even move it to the root of the repo, but please check the links to make sure that they are not broken

**Comment by casz** [comment]
no links to it from what I can see

**Comment by casz** [comment]
Moved to root :)

**Comment by ewelinawilkosz** [comment]
accepting this one but surely the content itself will be developed :)

**Pull request merged**
