### PR TITLE
Improve SecretSource Javadoc

### PR DESCRIPTION
**Pull request by chriskilding**
Improve the SecretSource class Javadoc to help implementors understand it. Give examples of scenarios when:

- It should return a value
- It should return Optional.empty()
- It should throw an IOException

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by chriskilding** [comment]
I've had a first go at defining when implementors should return Optional.empty and when they should throw an exception. Have a look and let me know how it can be improved

**Comment by chriskilding** [comment]
I'm implementing one at the moment and it's all kinds of fun 😉 

I would caveat that my understanding of how the SecretSourceResolver works is sketchy... IIRC the IOException is converted to unchecked and re-thrown (which should certainly stop the world, unless something catches that in turn?). But the way optionals are handled is trickier.

**Comment by casz** [comment]
I'd like to get a chance to review. I help implement improve the SecretSource for Vault so I have a good understanding 😁

**Comment by timja** [comment]
@chriskilding / @Jetersen anything else needs doing here?

**Comment by chriskilding** [comment]
Aside from Joseph's review, I'm thinking that maybe "the secret's value was not convertible to a String" should be an **un**recoverable error. The secret was found, so the source intended to provide it, but it's not compatible. I don't think it would be reasonable to progress along the SecretSource chain if this happens.

**Comment by chriskilding** [comment]
@Jetersen any update?

**Comment by Jetersen** [comment]
Do not consider my review blocking.

**Comment by chriskilding** [comment]
I've moved the 'not convertible to string' case into the unrecoverable errors section.

I also added the 'authN or authZ with backing store failed' case to unrecoverable errors, as this will be one of the most common error cases that SecretSource implementations will hit.

I think I'm now happy with it, so I will remove the WIP and let Tim and Joseph merge when they are happy with it.

**Comment by chriskilding** [comment]
any update?

**Comment by jetersen** [comment]
Missed the title change 🦖

**Pull request merged**
