### PR TITLE
[DEMOS] Add more examples to help with bitbucket casc

### PR DESCRIPTION
**Pull request by quentin-lpt**
Related to #1491 

I've added some extra examples in demos/jobs/bitbucket.yaml that should help for easier comprehension.

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by jetersen** [comment]
link to see current commit author: https://github.com/jenkinsci/configuration-as-code-plugin/commit/54f29841b11415132117091a8e34c3b7d54e4299.patch

@lpl-hosting 
You might want to set up an email alias on your GitHub account 🥇
https://help.github.com/articles/adding-an-email-address-to-your-github-account/

Or look into fixing your git user.email config 😅  
https://help.github.com/articles/setting-your-commit-email-address-in-git
then you would need to amend your commits: https://stackoverflow.com/a/3042512
after changing author

to get proper credit for your commits 🏆

**Review by jetersen — COMMENTED** [review]
These demos are usually backed by testing.

I'd also suggest removing the commented sections and add tests to validate those sections.

See one of these PRs as an example:
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1226
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1225

**Comment by lpl-hosting** [comment]
I've removed comment as you suggested but unfortunately I won't be able to write the groove test you asked (too hard for me!)

Thx for the feedback anyway, I hope my examples will still be good enough, it took me some long hours to discover them.

**Review by jetersen — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
LGTM

**Pull request merged**
