### PR TITLE
Add integration test for MSTestRunner

### PR DESCRIPTION
**Pull request by varyvol**
This adds an integration test for [MSTestRunner](https://github.com/jenkinsci/mstestrunner-plugin)

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [X] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by MRamonLeon** [comment]
It seems that you have to fix other tests asserting the default tool configurations because now there is a new tool, this one.

**Comment by varyvol** [comment]
I see a failure that seems related with my new test, but I don't understand why and it's passing locally for me.

**Comment by varyvol** [comment]
Maybe @timja @Jetersen  ?

**Comment by Jetersen** [comment]
@varyvol try and run all tests, this is not your new test failing it's a separate test failure.

I assume it has to do with MSTestRunner having some default that get's exported in the 
`ToolDefaultPropertiesExportBlacklistTest.export_tool_configuration:34` test
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1328/checks?check_run_id=511265402#step:5:693

**Comment by varyvol** [comment]
@timja @Jetersen solved now!

**Pull request merged**
