### PR TITLE
Include only needed classes in test jar

### LINKED ISSUE #798: When using configuration-as-code-tests on project "configuration" page dont work.
- [ 2.107.1 ] Jenkins version
- [ 1.7, 1.8 ] Plugin version
- [ Mac (but suppose all are affected) ] OS

When adding `configuration-as-code` with classifier `tests` into `test` scope requests that are calling `configuration` page are failing.

Maven dependency added:
```
    <dependency>
      <groupId>io.jenkins</groupId>
      <artifactId>configuration-as-code</artifactId>
      <version>${configuration-as-code.version}</version>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
```

Code that will fail when used as part of test
```
rule.createWebClient().goTo("configure");
```

Exception
```
org.apache.commons.jelly.JellyTagException: jar:file:/Users/ingwar/.m2/repository/org/jenkins-ci/main/jenkins-core/2.107.1/jenkins-core-2.107.1.jar!/jenkins/model/Jenkins/configure.jelly:59:84: <st:include> No page found 'config.jelly' for class io.jenkins.plugins.casc.impl.configurators.DescriptorConfiguratorTest$FooBar
```

Seems like class `DescriptorConfiguratorTest` should not be in this artefact, cause its part of this project tests..

On the other hand only this jar have `ConfiguredWithCode` and `JenkinsConfiguredWithCodeRule`

For a quick and dirty fix see https://github.com/jenkinsci/google-compute-engine-plugin/pull/54/commits/25f1ee850c40397b163e5a94f5b9ff304fa33f78

### PR DESCRIPTION
**Pull request by ingwarsw**
- Include only needed classes in `tests` artifact.
I have tried to move it to `src` but all this classes have references to `junit` internal classes so its not that easy.
If keeping it working will be hard in future than maybe extra subjects could be added just for those classes.

- Fixes #798 

Tested it externally on Google compute plugin.
Any idea how to test it locally?

### CODE REVIEW

**Comment by ingwarsw** [comment]
@casz I see it actually dont have them..
But Im almost 100% it did not have them before..

Will be hard to have them without extra project... :(

**Comment by ingwarsw** [comment]
Im refactoring it with own submodule.. will see if it will look ok..

**Comment by ingwarsw** [comment]
Ok it will not work that easily...
If I will create extra module `tests-support` then this module needs to be used as `test` dependency for `plugin` project.
But `tests-support` module itself needs class `ConfigurationAsCode` from `plugin`.
So we have circular dependency, which can be resolved by adding extra lib :)

Not worth it see https://github.com/jenkinsci/configuration-as-code-plugin/commit/3a00a232201a0385e1493ed24d46e7b0932b9df1..
Seems like this is best to leave it as its..

**Comment by casz** [comment]
When you say leave it as it is. You mean like in this PR or as we have it now on master? :smile:
it can become an overused word very quickly.

**Comment by ingwarsw** [comment]
`as in this PR` :)
pom is same as in master..
And config page in tests is working..

So improvement for sure..

**Comment by casz** [comment]
Perhaps rename `misc` package to something more significant?

**Comment by ingwarsw** [comment]
`junit` ?

**Comment by casz** [comment]
right, never mind 😄

**Comment by casz** [comment]
I wonder if we could provide dependencies at least for system-rules and have junit as a dependency that is provided by Jenkins plugin parent pom?

**Comment by ingwarsw** [comment]
It will not be easy without extra project..

**Comment by casz** [comment]
Argh :flushed: to solve the problem now, let's merge this.

I will look into a better solution if times allow it and that if at all possible.

**Pull request merged**
