### PR TITLE
make reincrementalify part of release

### PR DESCRIPTION
**Pull request by casz**
Thought I would save you the work @ndeloof and @ewelinawilkosz

### CODE REVIEW

**Comment by ndeloof** [comment]
I didn't noticed we had this `.ci/Jenkinsfile`. Seems it duplicated the root one used for jenkins.io infra, doesn't it? 
Better than such a shell you could set [completionGoals](http://maven.apache.org/maven-release/maven-release-plugin/prepare-mojo.html#completionGoals) to run `incrementals:reincrementalify` as part of maven standard release process.

**Comment by casz** [comment]
the `.ci/Jenkins` is not duplicated it is used over at http://code.praqma.net/ci/job/jenkins-configuration-as-code-plugin-release/ sadly it cannot be reached atm 😢 

My maven knowledge did not know of completionGoals 👍 
Then I don't understand why `incrementals-tool` did not take advance of this?

**Comment by ndeloof** [comment]
I'm not sure incrementals-tool can set a property consumed by another plugin. Anyway we can just use 
```xml
<properties>
  <completionGoals>incrementals:reincrementalify</completionGoals>
</properties>
```

I wonder about the role of  http://code.praqma.net/ci here, if there's something missing on jenkins.io infra we should get it added there.

**Comment by casz** [comment]
I recall @rtyler saying that jenkins.io infra does not yet support releasing 😢

related to [INFRA-1412](https://issues.jenkins-ci.org/browse/INFRA-1412) seems silly that you have to create a .travis.yml to automate your own release. I know [doktor-plugin](https://github.com/jenkinsci/doktor-plugin) did this

Sorry if I am tagging but I still think this deserves discussion.

**Comment by casz** [comment]
Tested it over at https://github.com/jenkinsci/kotlin-v1-stdlib-jdk8-plugin/commit/afc674665f767aeec664536c8b6fb64961fda48f works at intended 👍

**Comment by casz** [comment]
@ewelinawilkosz YAAaaa! no more typing `mvn incrementals:reincrementalify` 🎉

**Comment by casz** [comment]
Seems this going to be picked up by parent POM 👍

**Pull request merged**
