### PR TITLE
compare collection in Attribute

### PR DESCRIPTION
**Pull request by casz**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!

- [x] Please describe what you did

- [ ] Link to relevant GitHub issues or pull requests

- [ ] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org)

- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### Description

Fixed the FIXME!

### CODE REVIEW

**Comment by casz** [comment]
A test case would be nice

**Comment by timja** [comment]
could try removing the code and seeing if there's coverage for it?

**Comment by casz** [comment]
The `compare` uses the `equals` method inside `BaseConfigurator`.

The question is whether it is good enough. 😕

**Comment by casz** [comment]
Apache collections utils have a compare method that might be better. I read there should be some issues in how I currently added comparison

**Pull request merged**
