### PR TITLE
Enabled support for Groovy scripts

### PR DESCRIPTION
**Pull request by szandala**
New module in support allows user to run Groovy scripts inline,
but with semicolons ';' at the end of each line.
Or as separate script e.g. url or file
This satisfies:
https://issues.jenkins-ci.org/browse/JENKINS-55344
https://github.com/jenkinsci/configuration-as-code-plugin/issues/686

- [x] Please describe what you did

- [x] Link to issue you're working on if there's a relevant one

- [x] Did you provide a test-case to demonstrate feature actually works / issue is fixed ?

- [x] Please also consider adding a line to [CHANGELOG.md](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by szandala** [comment]
Attached file is an example, that can be run on fresh Jenkins.
I will add new one for Gerrit-Trigger to demos
[groovy_jcasc.yml.txt](https://github.com/jenkinsci/configuration-as-code-plugin/files/2712283/groovy_jcasc.yml.txt)

**Comment by szandala** [comment]
> a unit test would be nice

I would love to, but I have no bloody idea how to test it. Could You show me an example how to test it?

**Comment by casz** [comment]
There are plenty of unit tests to draw from :)

Just take one of existing unit test add your yml file with groovy script which should do the trick.

See https://github.com/jenkinsci/configuration-as-code-plugin/blob/67add8967cfa22210fbf5746123058cdd6a2f97c/plugin/src/test/java/io/jenkins/plugins/casc/core/JenkinsConfiguratorTest.java#L22-L32

**Comment by szandala** [comment]
Thanks, now I see the solution

**Comment by szandala** [comment]
Please check the test

**Comment by casz** [comment]
@szandala 
you might want to look into fixing your git user.email config 😅 
or set up an email alias on your GitHub account 🥇 
to get proper credit for your commits 🏆 
https://help.github.com/articles/adding-an-email-address-to-your-github-account/
https://help.github.com/articles/setting-your-commit-email-address-in-git
then to amend your commits: https://stackoverflow.com/a/3042512

**Comment by szandala** [comment]
Should be OK now, sorry for the inconveniance

**Comment by szandala** [comment]
> Why the hell would you want to mix groovy in yaml this way and not just rely on plain old groovy.init ?

I've already explained this: init.groovy.d is not being executed on JCasC reload. Furthermore: I prefer to keep configuration in one place, instead 2 separate location (init.groovy.d and CASC_JENKINS_CONFIG).

Last but not least, I honestly doubt JCasC will support 100% Jenkins configuration.

**Comment by szandala** [comment]
> Generally speaking doing such groovy scripting in JCasC deserve the initial goal to offer a simpler model, vs having to learn both groovy + jenkins APIs. Such script would prevent any attempt to offer configuration validation. So my :-1

Neither You have configuration validation for DSL jobs creation.
Simpler model is cool, I love it so much. But in init scripts I have:
- Gerrit-Trigger configuration
- builds archive location (setRawBuildsDir)
- dedicated updates-center.json certificate fetching (this can be done in Dockerfile, true)

Those are my 3 steps that I call Groovy to perform (maybe a few more I do not recall now). And I believe there will be someone who can imagine other Groovy-only use-case.

Last but not least, nobody is forced to use it. This is a feature which I call "last resort". Enabling this feature means that CasC can be used **immediately** by **anyone**, and You can continue to adjust other plugins on an own pace. Think about it.

**Comment by ndeloof** [comment]
> Neither You have configuration validation for DSL jobs creation.

yes indeed, and this is why I consider this job-dsl support as a quick-win short term solution, until we get adequate API in jenkins-core to offer native yaml support for jobs.

> Gerrit-Trigger configuration, builds archive location (setRawBuildsDir)

Those need to be fixed to support JCasC, as many others

> dedicated updates-center.json certificate fetching (this can be done in Dockerfile, true)

Plugin management and update center is a huge topic. We tried to support plugin installation but I'm convinced we need a larger debate on making plugin management fully configurable and usable outside jenkins web UI.

> This is a feature which I call "last resort"

Understand. In many places we made some feature possible by configuration, but at minimal this still produces a warning. Your proposed support could easily be packaged in a third party plugin, no need to offer this as part of JCasC even with a big "_don't use it_" warning.

**Comment by szandala** [comment]
You are right, about more work, about debate for plugins (I have some thoughts about it, but no good solution yet), about using third party elements.

> yes indeed, and this is why I consider this job-dsl support as a quick-win short term solution, until we get adequate API in jenkins-core to offer native yaml support for jobs.

Indeed! That is all I am talking about: there is NO YET support for some features. I want to convince my Team to bring into play JCasC, but they will resist until we cannot fully re-write current solution.

Isn't the configuration-as-code**-support** a "third party" element of the plugin?
As I see there are jobdsl, matrix support, my proposed groovy. In my opinion all here require a bit work.
I honestly think Groovy section fits here

**Comment by oleg-nenashev** [comment]
My usual use-case for Groovy Scripting is a dynamic configuration (e.g. creating Jobs and other entities only when some conditions are met). So I am +1 for having such Groovy scripting support in JCasC.

Regarding the location of the code...

* I agree with @ndeloof that ` configuration-as-code-support` is not a right location for it
* If I was a maintainer of JCasC, I would be +1 about adding it to the plugin code directly, But I am not, and I understand concerns raised by @ndeloof 
* There is no strict need to have the code in the JCasC plugin directly. It could be a separate plugin 
* Moving the functionality to another plugin causes another potential chicken-and-egg if somebody wants to manage plugins from JCasC. But it's as-designed I'd guess

@szandala my proposal would be to go forward with a separate plugin for Groovy-based management in JCasC. In addition to the proposed patch it may be possible to create Groovy Env Var resolver there and to add other sweet features.

**Comment by szandala** [comment]
@oleg-nenashev 
Thank You for supporting my idea ;-)

Regarding location: I do not want to have  separate plugin, because I will not have time to fully maintain it.
Furthermore: as You have noticed, it would be another chicken-egg problem, that I dislike. I'd like JCasC to be plugin put into base Jenkins.war one day, therefore I vote -1 for separate plugin.

For me support-sub-plugin is the best location. Groovy is meant to be supportive for JCasC, which fits for me.

**Comment by oleg-nenashev** [comment]
Support plugin is exactly the same as a new plugin. There is no
"sub-plugins" in Jenkins.

W.r.t bundling into the jenkins.war, it is already possible via
https://github.com/jenkinsci/custom-war-packager . Demo for JCasC:
https://github.com/jenkinsci/custom-war-packager/tree/master/demo/casc

**Comment by hawky-4s-** [comment]
I really like the idea of having groovy support in CasC as we are currently also using both combined. Like @szandala already stated, groovy can be used to configure unsupported plugins and more advanced usecases.
For us, the hot reload feature of CasC is nice to use to keep a Jenkins running without the need for restart preventing a service disruption.
We use init.groovy.d Groovy files to configure file credentials which are not supported yet and various other things. Some of those changes are lost, eg. the file credentials when CasC reload is applied.
To circumvent that, I wrote a Jenkins job which calls the logic of the init.groovy.d which can be executed after CasC reload to reapply the groovy scripts changes.

**Comment by ewelinawilkosz** [comment]
we have strong opinions regarding that topic and I'd like to have a discussion about it at next JCasC Office Hours meeting - we're trying to find a most suitable timeslot for that, I'll let you know here when we have the date

**Comment by ndeloof** [comment]
Just to resume my point of view :

JCasC is by design considering a model exposed by Jenkins components, that let us configure things in yaml. It uses conventions so we discover model for most components, and can get others just adopt those reasonable conventions with minimal impact.

Introducing Groovy support just get the scripting approach back, with need to maintain binary compatibility. Also Groovy being far more powerful comes with security impacts (JCasC only do support public attributes).

Yes, we support Groovy for jobs, but only _because_ we fully delegate to job-dsl plugin (until the hudson.model.Job type hierarchy get updated to offer a descent data model)

_if_ we introduce groovy as a workaround, we will just reduce need for plugins to get updated to be JCasC-compliant, and I can guess we still will have the same status in 2 years with no updates from plugins, and tons of groovy-workaround-scripts everywhere.

So I maintain my strong :-1 for this RFE. But if others involved in JCasC _really_ want this feature implemented, up to the community to maintain the beast.

**Comment by oleg-nenashev** [comment]
@hawky-4s- 
> To circumvent that, I wrote a Jenkins job which calls the logic of the init.groovy.d which can be executed after CasC reload to reapply the groovy scripts changes.

One of the ways to productize it would be to actually add a Groovy Hook to JCasC after loading (e.g. `post-jcasc`). In Jenkins Groovy Hooks are the simple extension point, and I believe it could be acceptable in this plugin (few lines of code).

**Comment by szandala** [comment]
So summary from :-)
**Why I need this feature?**

- there is no 100% JCasC coverage of Jenkins & all plugins
- even then there might be "some uniqe step", that cannot by done via simple yaml
- I do not want to split my initialization into init.groovy.d and JCasC

**Options how to introduce this feature**

1. As a part of support plugin (my favorite): this fits the best in my opinion, since Groovy is supposed to support where JCasC appears insufficient. If JCasC achieves near 100% coverage, this will stay as supportive solution. If someone doesn't want this feature, then He is free to omit it
2. As merge to main plugin: here I agree with @ndeloof , that this is not the goal of JCasC (it should base on public API) and it will be hard to miss sign that "plugins does not have to adapt".
3. As a separate plugin (my second choice). Honestly I lack time to prepare everything alone, neither will I have time to provide decent support for this solution. Last, but not least this may create another chicken-egg problem.

Regarding @oleg-nenashev 's idea as post-jcasc: I prefer to be able to freely use "groovy", whenever it is needed. I might need to do some yaml-supported task, groovy tak and again yaml-task.

**Comment by ewelinawilkosz** [comment]
Yesterday (Jan 16th 2019) we've decided to not merge this PR in a current form. 
@szandala will try to implement the feature as a separate plugin - @szandala please share repository on gitter channel when you start, I'm pretty sure there is more users interested in mixing groovy with JCasC in a current state, so feel free to jump in and contribute everyone!
I'm gonna keep this PR opened for a while - to make it easier to find out about the initiative for those who were not involved so far, but it will be gone once we have a final solution

**Comment by szandala** [comment]
I am moving this feature to separate plugin, please see:
https://github.com/szandala/jcasc-groovy

**Pull request closed without merging**
