### PR TITLE
Update parent and incrementals version

### PR DESCRIPTION
**Pull request by alecharp**
The plugin is still using a beta version of the incrementals extension.
This PR fixes that and also update the Jenkins Plugin parent pom version.

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by timja** [comment]
Enforcer failures:
```
[2019-12-18T15:32:48.113Z] Require upper bound dependencies error for org.hamcrest:hamcrest-core:1.3 paths to dependency are:

[2019-12-18T15:32:48.113Z] +-io.jenkins.configuration-as-code:test-harness:1.35-rc1009.14de9af361c3

[2019-12-18T15:32:48.113Z]   +-junit:junit:4.12

[2019-12-18T15:32:48.113Z]     +-org.hamcrest:hamcrest-core:1.3

[2019-12-18T15:32:48.113Z] and

[2019-12-18T15:32:48.113Z] +-io.jenkins.configuration-as-code:test-harness:1.35-rc1009.14de9af361c3

[2019-12-18T15:32:48.113Z]   +-org.jenkins-ci.main:jenkins-test-harness:2.56

[2019-12-18T15:32:48.113Z]     +-org.hamcrest:hamcrest-core:2.1

[2019-12-18T15:32:48.113Z] and

[2019-12-18T15:32:48.113Z] +-io.jenkins.configuration-as-code:test-harness:1.35-rc1009.14de9af361c3

[2019-12-18T15:32:48.113Z]   +-org.jenkins-ci.main:jenkins-test-harness:2.56

[2019-12-18T15:32:48.113Z]     +-org.hamcrest:hamcrest-library:2.1

[2019-12-18T15:32:48.113Z]       +-org.hamcrest:hamcrest-core:2.1

[2019-12-18T15:32:48.113Z] ]
```

**Comment by alecharp** [comment]
sorry I missed that. On it.

**Comment by timja** [comment]
Can’t label the PR from my phone :( will sort before release unless someone else wants to add chore

**Comment by casz** [comment]
Done @timja 👍

**Pull request merged**
