### PR TITLE
Use jackson api plugin in test harness

### PR DESCRIPTION
**Pull request by jetersen**
to avoid upperbounds conflict in bom and other plugins.

https://github.com/jenkinsci/bom/pull/294

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by jglick** [comment]
I am also seeing a PCT error between `configuration-as-code` 1.43 and `junit` 1.37 which I am guessing is related:

```
java.lang.NoSuchMethodError: io.jenkins.plugins.casc.ConfigurationAsCode.toYaml(Lio/jenkins/plugins/casc/model/CNode;)Lio/jenkins/plugins/casc/snakeyaml/nodes/Node;
	at io.jenkins.plugins.casc.misc.Util.toYamlString(Util.java:152)
	at io.jenkins.plugins.junit.storage.JunitTestResultStorageConfigurationTest.should_support_configuration_export(JunitTestResultStorageConfigurationTest.java:35)
```

**Comment by timja** [comment]
> I am also seeing a PCT error between `configuration-as-code` 1.43 and `junit` 1.37 which I am guessing is related:
> 
> ```
> java.lang.NoSuchMethodError: io.jenkins.plugins.casc.ConfigurationAsCode.toYaml(Lio/jenkins/plugins/casc/model/CNode;)Lio/jenkins/plugins/casc/snakeyaml/nodes/Node;
> 	at io.jenkins.plugins.casc.misc.Util.toYamlString(Util.java:152)
> 	at io.jenkins.plugins.junit.storage.JunitTestResultStorageConfigurationTest.should_support_configuration_export(JunitTestResultStorageConfigurationTest.java:35)
> ```

Seems to pass for me locally, but here's a PR to bump it to latest:

https://github.com/jenkinsci/junit-plugin/pull/174

**Comment by timja** [comment]
@jetersen any reason to hold this back?

**Comment by jetersen** [comment]
@timja it needs to be backported due to plugin bom 2.204.x support and down.

**Comment by timja** [comment]
> @timja it needs to be backported due to plugin bom 2.204.x support and down.
> 
> But no nothing is blocking it.

let's see if we need it, better to at least fix the ones we can

**Pull request merged**
