### PR TITLE
cleanup dependencies

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
What is the justfication for that?
How do we benefit from using a bundled lib and risking to get binary conflicts?

**Comment by ndeloof** [comment]
right, missing "provided" scope

**Comment by ndeloof** [comment]
reason is that we don't depend on structs plugin, we depend on @Symbol annotation as provided by core. And due to classpath issue I had to make this explicit

**Comment by ndeloof** [comment]
still have classpath issue, so closing until I better understand the root cause

**Pull request closed without merging**
