### PR TITLE
Integration test with baseline of next LTS

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Integration test with 2.277 (weekly baseline of next LTS)

Use Jenkins 2.277 while waiting for the release of Jenkins 2.277.1.  See [LTS release checklist](https://github.com/jenkins-infra/release/issues/137).

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
Some other deps need updating due to spring security etc, active directory and ldap at least

**Comment by MarkEWaite** [comment]
The current test failure is beyond my depth.  If someone else would like to investigate why a new Jenkins core version includes:

```
mavenGlobalConfig:
  globalSettingsProvider: "standard"
  settingsProvider: "standard"
```

that is left to them.

**Comment by timja** [comment]
Thanks Mark I'll take it from here

**Comment by jetersen** [comment]
@timja I believe this is related: https://github.com/jenkinsci/configuration-as-code-plugin/pull/925

**Comment by timja** [comment]
It's just this https://github.com/jenkinsci/jenkins/pull/5008

**Comment by timja** [comment]
This test https://github.com/jenkinsci/configuration-as-code-plugin/blob/52ed3feebaa5e32e119c5aed35361bf8142e8ce7/integrations/src/test/java/io/jenkins/plugins/casc/MSTestRunnerTest.java#L26 causes there to be an additional descriptor in the export by the looks of it, only occurs if you run all tests https://github.com/jenkinsci/configuration-as-code-plugin/pull/1577/commits/cf7293d2c91b265a0a2d0837c1a913572e41c652 might help =/

**Pull request merged**
