### PR TITLE
Add 'jobs' samples in demo

### PR DESCRIPTION
**Pull request by yogeek**
Here is a quite complete example of a bitbucket organization folder. I thought it could be interesting to add it to the demos samples to help people like me who struggled with different part of seed jobs. (the 'traits' for example are not obvious to understand as some of it are not currently possible in pure DSL)
Hope it will help !

### CODE REVIEW

**Comment by ndeloof** [comment]
Could you please move the documentation on seed-jobs creation in a dedicated doc ?
As we'd like to get SeedJob configurator hosted by job-dsl plugin this would make this move easier

**Comment by yogeek** [comment]
@ndeloof Do you mean I should move the [How to create initial "seed" job](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md#how-to-create-initial-seed-job) section from the main [README.md](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md) to the [docs](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/docs) folder ? (maybe in a `seed-jobs.md` ?)

**Comment by ndeloof** [comment]
yes indeed

**Comment by yogeek** [comment]
done !

**Comment by casz** [comment]
@yogeek would you be will to associate the commits with your github user https://help.github.com/articles/adding-an-email-address-to-your-github-account/ 😅

**Comment by yogeek** [comment]
@casz  sorry for that, I changed of dev environment and did not set up git config for the repo properly...As I prefer to keep the email in github as is, I tried to squash my "wrong" commits into a good one (with good "author" field) but it seems that it picks one too many... Sorry about that
Maybe a cleaner solution here would be to close this PR and I will open another one. 
If it is ok for you, I will do that.

**Comment by casz** [comment]
We'll live without the commit history, the merger can always change the squashed and merged commits but just wanted you to get the credit 😄

**Comment by yogeek** [comment]
@casz ok so we keep it like this ? Thank you for your help and sorry again for the trouble :grin:

**Pull request merged**
