### PR TITLE
introduce ConfigurationContext and Listener

### PR DESCRIPTION
**Pull request by ndeloof**
based on ConfiguratorContext proposed by @oleg-nenashev on https://github.com/jenkinsci/configuration-as-code-plugin/pull/362

`ConfigurationContext` do host all the CasC config so we can invoke `check` without side effect on another thread.

### CODE REVIEW

**Comment by ndeloof** [comment]
I've detected a side effect : on export `version` is set as enum name `ONE`, not value `"1"`. I'm not sure how to tweak stapler to fix this. Just a minor issue anyway

**Comment by casz** [comment]
@ndeloof did you fix it in the rebased commit? 🤔

**Comment by ndeloof** [comment]
@casz no. We won't suffer this as we only have `ONE` as enum value, so comparison with default always exclude this from export. But once we have some new value added this will export name vs value.

**Comment by oleg-nenashev** [comment]
It's not exactly what I have designed, but should work

**Pull request merged**
