### PR TITLE
move all init logic to special rule @ConfiguredWithCode

### PR DESCRIPTION
**Pull request by lanwen**
relates to #95

this encapsulates the way of test setup, so we can concentrate on functional requirements in methods with just nice annotation `@ConfiguredWithCode`

### CODE REVIEW

**Comment by ndeloof** [comment]
Maybe I'm the old-style man here bu I don't feel the annotation "declarative" approach to be more readable vs plain imperative `ConfigurationAsCode.configure(x)` for unit testing.
But that's just personal feeling, I'm definitively not against those changes if other agree with them.

**Comment by lanwen** [comment]
Unit tests should not contain preparation code. It's Rule. 

Please read Code Smells chapter in 
image

annotation is the simplest way to parameterize cases with the resource path.

**Comment by ndeloof** [comment]
For sure this is a nice reference, but I don't consider
```java
 public CodeConfiguratorRunner config = new CodeConfiguratorRunner();

 @Rule
 public RuleChain chain = RuleChain.outerRule(j).around(config);
  		  
 @Test
 ConfiguredWithCode(value = "AgentProtocolsTest.yml")
```

to be "simpler" than just
```java
ConfigurationAsCode.configure(getResourceAsStream("ActiveDirectoryTest.yml"));
```

Same applies to annotation soup. I've seen too much Spring/JavaEE code with more annotations than actual code to consider this a _solution_.

But as I said, just my personal feeling, not a blocker here. Nothing agains you, don't see here any attack agains your own convictions :)

By the way, yes I've read many of those books, but with 20 years experience in coding I now have a way more pragmatic approach, and I'm **not** saying I'm right doing this !

**Comment by lanwen** [comment]
For instance - changing the read config implementation requires all tests rewrite.
Jenkins has cool `Recipe` annotations, but they called before Jenkins instance is fully initialized :(

Yep, the rules in this form look a bit ugly, but its the common part of all tests which can be safely copypasted and ignored. But in the method, we have ready-to-check state, and nothing disturbs us from test logic.

With junit5 (i'm dreaming that Jenkins will get it once) it will be hidden completely with same semantics for tests.

As any kind of modularization and encapsulation, this serves better for maintainability.

**Comment by oleg-nenashev** [comment]
We could just create a new `JenkinsConfigAsCodeRule` and hide the the Rule chain logic there

**Comment by ndeloof** [comment]
I use to rely on `extends HudsonTestCase` and now have to write `@Rule JenkinsRule j = new JenkinsRule()`. 
Modern testing is such an improvement in my daily job

...
(just trolling here, feel free to just ignore this :P)

**Comment by ewelinawilkosz** [comment]
you ok with new version @oleg-nenashev ? I could merge today

**Comment by lanwen** [comment]
can be merged with squash

**Comment by lanwen** [comment]
wow, that was a very dirty merge :) But thanks anyway.

**Comment by ewelinawilkosz** [comment]
thank you!
and why dirty? @MadsNielsen was asking for the merge for some time already :]

**Comment by lanwen** [comment]
Because of bunch of dummy merge-commits :) That's why I asked squash-merge :)

**Comment by ewelinawilkosz** [comment]
oh... damn, I went too fast, sorry

**Comment by MadsNielsen** [comment]
@lanwen No worries...we're moving ahead :P

**Comment by oleg-nenashev** [comment]
Sorry for not reviewing timely. the new version LGTM

**Pull request merged**
