### PR TITLE
setting global env vars added to demos

### PR DESCRIPTION
**Pull request by ewelinawilkosz**
@ndeloof setting global env variables with globalNodeProperties works very nice, 
just to make sure - your PR #183 is not providing the same feature for setting env vars on build agents, right?

### CODE REVIEW

**Comment by ndeloof** [comment]
yes indeed my fix is all about jenkins master's node properties + global node properties.
looking into this issue I wonder we miss global support for DescribableLists : we can get this list by a setter, then replace all values from configured list of elements. This would be a new type of Attribute detection where no setter method exists

**Comment by ewelinawilkosz** [comment]
ok, cool - I will extend this PR with `nodeProperties example`(I only have `globalNodeProperties ` so far) and then merge

**Comment by ndeloof** [comment]
@ewelinawilkosz is this still accurate ?

**Comment by ewelinawilkosz** [comment]
I'd say so, but my Jenkins fails after I instal 0.10-alpha and try to restart :( so verification in progress
```
java.lang.IllegalStateException: Expected 1 instance of hudson.PluginManager$PluginUpdateMonitor but got 0
	at hudson.ExtensionList.lookupSingleton(ExtensionList.java:436)
	at hudson.PluginManager$PluginUpdateMonitor.getInstance(PluginManager.java:2015)
	at hudson.maven.PluginImpl.init(PluginImpl.java:58)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1064)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1098)
	at jenkins.model.Jenkins.<init>(Jenkins.java:900)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:250)
```

**Comment by ewelinawilkosz** [comment]
after spending hours on fixing my jenkins I discovered demo was already updated :joy: 
so no, not accurate anymore

**Pull request closed without merging**
