### PR TITLE
Fix classloading in snakeyaml

### PR DESCRIPTION
**Pull request by timja**
Fixes https://github.com/jenkinsci/configuration-as-code-plugin/issues/1339

Haven't tested interactively yet, but just copied from https://github.com/jenkinsci/configuration-as-code-plugin/pull/1205/files

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by Jetersen** [comment]
Why was this reintroduced?

**Comment by Jetersen** [comment]
Oh the PR was closed 🤔

**Comment by timja** [comment]
> Oh the PR was closed 🤔

a different PR was used and I forgot that I made a PR for this a long time ago...

**Comment by oleg-nenashev** [comment]
TBH I am afraid about changing the default classloader without merging it with the default Jenkins one. I am not sure what is the potential impact, but it is prone to failures if any plugin classes are needed

**Comment by timja** [comment]
tested manually, it works...

> TBH I am afraid about changing the default classloader without merging it with the default Jenkins one. I am not sure what is the potential impact, but it is prone to failures if any plugin classes are needed

this restores the classloader to what it was before I believe

**Comment by amuniz** [comment]
I guess this comes from #1332. If so, why we didn't get any test failure in that PR?

**Comment by oleg-nenashev** [comment]
JTH has different classloading from production. If you make a change in a classloading logic, it is highly recommended to test it manually or in ATH.

FTR https://issues.jenkins-ci.org/browse/JENKINS-41827

**Comment by Jetersen** [comment]
Would be good to have a basic ATH test in JCasC that would validate class loading works 🤔

**Comment by ryanseanp** [comment]
This class loading in release 1.38 appears to be breaking the jobDsl(additionalClasspath: '') pipeline step. Issue is not seen in release 1.36. Do you have an idea why this would be affecting the jobDsl plugin's classpath?

**Pull request merged**
