### PR TITLE
Closes #567 - RoleStrategy Demo

### LINKED ISSUE #567: Move RoleStrategy demos from test to the demo folder
Currently YAML samples are listed here: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/integrations/src/test/resources/io/jenkins/plugins/casc

It would be great to have them also listed in the demo directory

### PR DESCRIPTION
**Pull request by jonbrohauge**
Fix for #567

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Is it a part of https://jenkins.io/blog/2018/10/01/hacktoberfest/ ?
Or just a quick fix?

**Comment by jonbrohauge** [comment]
@oleg-nenashev The _hacktoberfest_ tag did catch my eye 😁  I would have done a PR for at anyway

**Comment by oleg-nenashev** [comment]
Yeah. I am asking, because we need to label issues correctly to make them properly counted

**Comment by jonbrohauge** [comment]
ok... Looked at my [contributions](https://hacktoberfest.digitalocean.com/stats/jonbrohauge) and there I'm marked for 1 in-progress.

**Pull request merged**
