### PR TITLE
Initiate new LTS baseline 2.361.x

### PR DESCRIPTION
**Pull request by krisstern**
## Checklist
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes (N/A)
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue. (N/A)

## Description
Concerns https://github.com/jenkins-infra/release/issues/275

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by jetersen** [comment]
I think we need a newer bom specialfly for the integration tests

**Comment by NotMyFault** [comment]
> I think we need a newer bom specifically for the integration tests

Tests should now pass with https://github.com/jenkinsci/configuration-as-code-plugin/pull/2095 merged, rebasing with master will show the results 🤞🏻

**Comment by jetersen** [comment]
@krisstern has setup the PR with no permissions for maintainers to push updates 😅

So I cannot rebase the PR or merge in master.

**Comment by krisstern** [comment]
@jetersen I have already enabled "Allow edits and access to secrets by maintainers" for this PR, it's weird you cannot push updates to it...

Anyways I have fetched the latest updates to the `master` branch and have rebased the PR following it.

**Comment by NotMyFault** [comment]
More work needs to be done, I created https://github.com/jenkinsci/configuration-as-code-plugin/pull/2099 as test run.

Regular tests are passing now.

**Comment by jetersen** [comment]
@krisstern odd I still cannot do merge or push to this PR, however seems like @timja was able to.

**Comment by krisstern** [comment]
@jetersen Yeah, that's pretty odd...

**Review by NotMyFault — APPROVED** [review]

**Comment by timja** [comment]
> @krisstern odd I still cannot do merge or push to this PR, however seems like @timja was able to.

yup i could at least in github ui

**Comment by jetersen** [comment]
> yup i could at least in github ui

I tried both locally using `gh pr checkout` and also looking at the GitHub UI the option is not available. 😭

**Review by jetersen — APPROVED** [review]

**Comment by NotMyFault** [comment]
LGTM doesn't look good to me this time, possibly an auto merge blocker? (If we get a green light on ci.j)

**Comment by jetersen** [comment]
Not a blocker

**Pull request merged**
