### PR TITLE
Add Gitter Q&A tab to the New Issue dialog

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Submitting it to get a feedback. I used a new GitHub feature to make the Vulnerability Reporting process and Q&A more visible on the new Issue creation dialog.

Before merging, we need to agree whether the `question` template is still needed

Sample from WinSW:

image

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by daniel-beck** [comment]
GitHub has support for the security vulnerability category as soon as you have any categories, and a security policy, IIUC.

See https://github.com/jenkinsci/configuration-as-code-plugin/issues/new/choose which links to the policy excerpt on GitHub.

**Comment by oleg-nenashev** [comment]
You are right @daniel-beck 🤦‍♂ . I should have checked this template as well

**Comment by Jetersen** [comment]
I think you can safely remove the `Need help thing?`

**Comment by oleg-nenashev** [comment]
@Jetersen 

> I think you can safely remove the Need help thing?

See the pull request title, waiting for feedback

**Comment by oleg-nenashev** [comment]
Let's keep both for now

**Pull request merged**
