### PR TITLE
Add demo for mesos cloud configuration

### PR DESCRIPTION
**Pull request by minitux**
Just add a new sample to configure the mesos plugin and add a slave.

### CODE REVIEW

**Comment by gbastkowski** [comment]
Do You have an idea now to add the "Mesos Offer Selection Attributes" to the mix?

**Comment by ewelinawilkosz** [comment]
I'm going to merge this PR as soon as I verify the configuration - not that I don't trust you, but better safe than sorry :)

**Comment by ewelinawilkosz** [comment]
I'm not sure what you're asking about @gbastkowski - I assume if @minitux provided sample configuration the plugin is supported (and we will confirm that soon), are you talking about something else?

**Comment by gbastkowski** [comment]
Nevermind, I just wanted to try the sample in our setup.
The answer to my question is:
```
            slaveAttributes: >
              {"rack":"jenkins-build-agents"}
```

**Comment by ewelinawilkosz** [comment]
oh, it was 'how', not 'now' - now I get it
and thanks, we may update the example with that part

**Comment by minitux** [comment]
@gbastkowski we don't use this option in our configuration. It really works.
Thanks for increase the example  :)

**Pull request merged**
