### PR TITLE
[ad-hoc] EC2 Plugin v1.42 parameters deprecated 

### PR DESCRIPTION
**Pull request by rlnchow**
- *Plugin version:* 1.20
- *Jenkins version:* 2.164.3
- *OS:* Alpine

### Description

EC2 Plugin 1.43 version deprecated couple of parameters. Previous example will fail on validation.

- Updated example with correct parameters.

### CODE REVIEW

**Comment by rlnchow** [comment]
@timja Can you review this PR?

**Comment by timja** [comment]
@thoulen any chance of a release for the ec2 plugin to fix the jcasc compatibility issues?

**Comment by rlnchow** [comment]
@timja Are we merging this one into master?

**Comment by thoulen** [comment]
> I've been hoping the ec2 plugin would get released as this has been fixed on master...

the new ec2-plugin release will be in 1 or 2 days

**Pull request merged**
