### PR TITLE
[JENKINS-51469] Add Essentials configuration to CasC tests

### PR DESCRIPTION
**Pull request by batmat**
This PR is based off `configuration-as-code-0.5-alpha` on purpose.
On my machine, `mvn clean verify` is successful.

But if I update (i.e. merge or rebase) on latest `master` it fails. 

It fails with the following error:

```
[SEVERE][2018-05-22 08:37:32] Failed ConfigurationAsCode.init (from jenkins.InitReactorRunner$1 onTaskFailed)
java.lang.Error: java.lang.reflect.InvocationTargetException
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1068)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	... 8 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: jenkins: error configuring <jenkins> with <jenkins> configurator
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:339)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:280)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:252)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:155)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:134)
	... 13 more
Caused by: org.jenkinsci.plugins.casc.ConfiguratorException: Invalid configuration elements for type class hudson.model.Hudson : metricsaccesskey
	at org.jenkinsci.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:200)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:44)
	at org.jenkinsci.plugins.casc.JenkinsConfigurator.configure(JenkinsConfigurator.java:24)
	at org.jenkinsci.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:335)
	... 17 more
```

### CODE REVIEW

**Comment by batmat** [comment]
@oleg-nenashev that is right, the test does not check everything that could be, I filed it as-is for now since it does fail locally for me though. Failing the exact same way as in essentials tests currently on the `master` branch. So I figured it would be enough as a first stab and help for CasC devs to figure out what got changed.

**Comment by batmat** [comment]
I bisected the issue:

```
git bisect log                                                                                                                                           37e4cbb
git bisect start
# good: [8921814751e0465ba31b853b9adec18bb557f0ff] [maven-release-plugin] prepare release configuration-as-code-0.5-alpha
git bisect good 8921814751e0465ba31b853b9adec18bb557f0ff
# bad: [4055b206726c069579cf38543bc274ca4d740657] Avoid calling as sequence on a null object (#215)
git bisect bad 4055b206726c069579cf38543bc274ca4d740657
# bad: [8de6b0b94a56968100180bd7f9ae96818257d7e4] Shortcut notation to programmatically set scalar values
git bisect bad 8de6b0b94a56968100180bd7f9ae96818257d7e4
# good: [7d2a93d1ce2d716de41b4f82e31d427e1b55e9eb] Run configuration before jobs are loaded.
git bisect good 7d2a93d1ce2d716de41b4f82e31d427e1b55e9eb
# good: [533a77e49d95d144806d3d73b1983bb710d1a49e] link to export live instance as Yaml
git bisect good 533a77e49d95d144806d3d73b1983bb710d1a49e
# bad: [d9e751109a444cd24c9070ab067261e8acfbaed1] fix ActiveDirectoryTest (jenkinsInternalUser was ignored)
git bisect bad d9e751109a444cd24c9070ab067261e8acfbaed1
# bad: [37e4cbb3803c4f70450a1ad69a3b564863773739] introduce a model for configuration tree so we abstract away fro snakeyaml API (and could later switch to another lib) and can restrict supported model to Map|List|Scalars
git bisect bad 37e4cbb3803c4f70450a1ad69a3b564863773739
# first bad commit: [37e4cbb3803c4f70450a1ad69a3b564863773739] introduce a model for configuration tree so we abstract away fro snakeyaml API (and could later switch to another lib) and can restrict supported model to Map|List|Scalars
```
gentle ping @ndeloof @ewelinawilkosz thanks!

**Comment by ewelinawilkosz** [comment]
just from the top of my head - a lot of configurators that were under jenkins root element are moved to unclassified now, maybe you need to fix your yaml?

**Comment by batmat** [comment]
FTR, fails the expected way:
image

**Comment by batmat** [comment]
@ewelinawilkosz possibly. Checking the docs. That rings some bell somewhere, but I didn't follow closely your changes TBH indeed.

**Comment by ewelinawilkosz** [comment]
the docs... I should review the dosc and make sure everything is aligned. didn't do that before :(

**Comment by batmat** [comment]
@ewelinawilkosz we can adjust the yaml if need be. I've just no idea as to what to do actually. cc @ndeloof

**Comment by ewelinawilkosz** [comment]
sure,
so in https://github.com/jenkinsci/configuration-as-code-plugin/commit/ca82f275b0681ed15c45519b5d8e05937e130187 @ndeloof moved all unclassified descriptors under separate root element - I assume most of the plugins to end up there
here is an example for mailer
https://github.com/jenkinsci/configuration-as-code-plugin/blob/1070b7da6cfbadffec0dc8bbe5ce4b78c1315337/src/test/resources/org/jenkinsci/plugins/casc/MailerTest.yml
I've created #217 to fix that

**Comment by ndeloof** [comment]
indeed, as part of the "export" feature development, as I can't compare current Jenkins instance state with a reference state (one can't build two `Jenkins` objects within the same JVM), it sounded bad we dump data for all unclassified descriptors. By the way this could help plugin authors adopt those categories (I've seen few of them being 'unclassified' but which should belong an existing category)

**Comment by batmat** [comment]
@ndeloof @ewelinawilkosz adapted the test to the new format. I believe, once the PR build is green, it would be valuable to merge this to more easily track compatibility with what we use on Essentials side. Thanks!

**Comment by batmat** [comment]
Failure here because of FindBugs failing on `master` branch...

**Comment by batmat** [comment]
Merci Nicolas.

**Pull request merged**
