### PR TITLE
Fix wrong index for override merge strategy 

### PR DESCRIPTION
**Pull request by jonesbusy**
Hi,

This PR update some test of OverrideMergeStrategyTest.

It shows there is still multiple issue with merging for this strategy.

To be honest I have no idea how to fix it :(

FYI https://github.com/jenkinsci/configuration-as-code-plugin/pull/1904

Any idea ? @srz-zumix @LinuxSuRen Is it a supported use case ?

Thanks!

Those test are failing

```
Error:  Failures: 
Error:    OverrideMergeStrategyTest.multipleKeys:105 unexpected systemMessage with override merge strategy expected:<[hello b]> but was:<[overwrite]>
Error:    OverrideMergeStrategyTest.simpleStringValue:75 unexpected systemMessage with override merge strategy expected:<hello b> but was:<null>
```

### CODE REVIEW

**Comment by srz-zumix** [comment]
Great tests!

https://github.com/jenkinsci/configuration-as-code-plugin/blob/b1b8cbc67af4ca4984736cc7dd17775d9b22d319/plugin/src/main/java/io/jenkins/plugins/casc/yaml/OverrideMergeStrategy.java#L51

It can be fixed by modifying this as follows.
Since `i` is a map2 index, it seems that was overwriting it in the wrong position.

```
map.getValue().set(map.getValue().indexOf(tuple), t2);
```

**Comment by jonesbusy** [comment]
Thank you for the hint, I will try to do the fix today.

Regards,

**Comment by jonesbusy** [comment]
New PR here : https://github.com/jenkinsci/configuration-as-code-plugin/pull/1917

**Comment by jetersen** [comment]
Not sure why you created a new PR. You can easily add more commits by pushing to your existing branch.

**Pull request closed without merging**
