### PR TITLE
Include more git plugin demo settings

### PR DESCRIPTION
**Pull request by MarkEWaite**
## [JENKINS-69281](https://issues.jenkins.io/browse/JENKINS-69281) Include more git settings in demo files

Add more examples of git plugin and git client plugin configuration.  Includes minor changes to match format of configuration as generated by the configuration as code plugin "View configuration".

See https://github.com/jenkinsci/git-client-plugin#configuration-as-code-sample for the matching documentation in the git client plugin.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- ~~Did you provide a test-case? That demonstrates feature works or fixes the issue.~~

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
This doesn't seem like great UX for the user.

Why are these stored separately from the rest of the Git plugin configuration?

**Review by jetersen — APPROVED** [review]

**Comment by MarkEWaite** [comment]
> This doesn't seem like great UX for the user.
> 
> Why are these stored separately from the rest of the Git plugin configuration? i.e. I mean the UI config, not the jcasc config.

Because they are configured from the "Manage Jenkins" --> "Configure Global Security" page rather than being configured from the "Manage Jenkins" --> "Configure System" page.

**Comment by MarkEWaite** [comment]
The failing CI on JDK 8 with GitHub actions seems like it is out of scope for this pull request.  I assume someone else will need to investigate that failure.

**Comment by jetersen** [comment]
@MarkEWaite the CI for Jenkins also failed, usually that indicates a failure.

At least the GitHub CI simply follows what Jenkins CI is doing.

**Comment by jetersen** [comment]
@MarkEWaite The failure is pretty valid: https://github.com/jenkinsci/configuration-as-code-plugin/runs/7728725903?check_suite_focus=true#step:4:1108

**Comment by timja** [comment]
> Because they are configured from the "Manage Jenkins" --> "Configure Global Security" page rather than being configured from the "Manage Jenkins" --> "Configure System" page.

Yes, but why? isn't this configuration for the Git plugin, it seems odd to me that a user needs to go to multiple places for it =/

**Comment by MarkEWaite** [comment]
> Yes, but why? isn't this configuration for the Git plugin, it seems odd to me that a user needs to go to multiple places for it =/

We chose to place it in the security configuration because it is generally a smaller page than the configuration system page.  It seemed to me to be specific to system security so was better suited to the security page rather than the large "Configure system" page.

**Comment by MarkEWaite** [comment]
I'm closing this pull request since the automated test of the GitToolInstallation does not recognize `security` as a valid top level entry.  I'm sure there is some way to teach that test to recognize it, but I don't have the time to do that investigation.

Users can use the example in the [git client plugin documentation](https://plugins.jenkins.io/git-client/#plugin-content-configuration-as-code-sample) and can read more about the option in that location as well.

**Comment by jetersen** [comment]
We need to bump the Jenkins Core or split test integration to use it owns bom version. 😅 

Not sure it required much looking, so sad to see you close the PR. Maintainer can usually contribute to open PRs.
https://github.com/jenkinsci/configuration-as-code-plugin/blob/b115510c74cae2dc7b4486b7876b942c5422c07b/pom.xml#L27

**Comment by MarkEWaite** [comment]
@jetersen I'm happy to reopen the pull request if it will allow others to help.  I know that I won't be able to do more with this pull request and I didn't consider it valuable enough to spend the time of others on it.

**Pull request closed without merging**
