### PR TITLE
Issue #279 - Detach Configurator API to a separate plugin, introduce Configurator Context

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Addresses #279 

- [x] - Configurator API is now a separate plugin, which includes reusable API and primitive implementations
- [x] - `BaseConfigurator` now does not depend on `ConfigurationAsCode` and `ObsoleteConfigurationMonitor` instance directly. Instead of that, a new pluggable `ConfiguratorContext` is introduced. It allows to use the configuration logic in other use-cases without JCasC (or to have customizable JCasC settings, e.g. for config verification)
- [x] - `ConfiguratorContext` is stored in TLS, so there is no need to pass it through the entire API => no API of existing implementations
- [x] - `ConfiguratorException` automatically saves context, so the issues can be distinguished by handlers

@ndeloof @ewelinawilkosz @casz @gautamabhishek46

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Probably `dryRun` flag should be also passed through the context so that it can be easily configured

**Comment by oleg-nenashev** [comment]
> I'm not a big fan of using ThreadLocal to avoid an explicit parameters.

Me too. The only reason for that was to avoid changing `configure/check` API interfaces. If you prefer, I could rework it

> Also unclear to me why you want to have a separate API plugin (didn't got explanation on #279. 
> Do you have some concrete use-case in mind ? 

Configurator API can be used in other plugins which need YAML => Object conversions. 
  * https://github.com/jenkinsci/simple-pull-request-job-plugin
  * https://github.com/jenkinsci/yaml-project-plugin
  * https://github.com/jenkinsci/yaml-axis-plugin
  * etc.

Configurator API also has advantages for JCasC itself:

* Configurator API may stay compatible with `2.60.3` when JCasC moves on to newer versions. It allows plugin developers to adopt new APIs without bumping Jenkins core
* Unbundling Configurator API allows setting boundary between API and implementation. Before this PR `ConfigurationAsCode` was directly used in classes like `DataBoundConfigurator`, and it amay have caused issue in the future. OTOH `ConfiguratorContext` can be added to the config without unbundling

> This make JCasC bundling into jenkins harder imho, I avoided having third party plugins dependency to ensure JCasC is just a drop-in plugin.

JCasC is not fully drop-in, it declares dependencies on several plugins. I totally agree with minimizing number of deps, but detaching API may make sense taking justification above. Anyway, to be discussed

**Comment by ndeloof** [comment]
> Configurator API can be used in other plugins which need YAML => Object conversions.

I think this is the exact intent for [JEP-205 DataBoundModel](https://github.com/jenkinsci/jep/pull/141) so would better be hosted here.


> Configurator API also has advantages for JCasC itself:
> Configurator API may stay compatible with 2.60.3 when JCasC moves on to newer versions. It allows plugin developers to adopt new APIs without bumping Jenkins core

Wrong. If we offer a 2.60.3 API we need to provide an implementation for same version (or this would just be useless) and as such we will have two branches to maintain (2.60.3 + more recent core). If we do so having an API plugin is no benefit for us, just makes installation more complex with risk for incosnsistencies.

> Unbundling Configurator API allows setting boundary between API and implementation. Before this PR ConfigurationAsCode was directly used in classes like DataBoundConfigurator, and it amay have caused issue in the future. OTOH ConfiguratorContext can be added to the config without unbundling

Your last refactoring make this boundaries more explicit. If you think we should have a dedicated API maven module, I'm fine with that, but please not a _plugin_. Reference for ConfigurationAsCode.get within other component can be replaced by your proposed `ConfigurationContext`, could you maybe submit a separated PR for this ? imho this one mixes too much opinionated changes.

> JCasC is not fully drop-in, it declares dependencies on several plugins

yes, optional dependencies for custom configurators, which I want to be hosted by target plugins. JCasC should have no dependency.

**Comment by ndeloof** [comment]
A major issue I can see with `ConfigurationAsCode.get()` is that we get into risks for race condition, with two concurrent `check` payload using distinct configs. Use of a `ConfigurationContext` is a cleaner afaict. Maybe it would make sense for this one to also handle the Configurator's lookup ?

**Comment by oleg-nenashev** [comment]
I will take a look. Generally I would be rather aware about race conditions
between configuration CLIs or between CLI and initializer

**Comment by ndeloof** [comment]
proposal to detach API in a plugin has been rejected

**Comment by oleg-nenashev** [comment]
Reopening for the discussion

**Comment by timja** [comment]
could you resolve conflicts @oleg-nenashev so we can see where this is at with the code of this year.

**Comment by casz** [comment]
@oleg-nenashev said he wouldn't deal with conflicts as I recall from the meeting 😆

**Comment by oleg-nenashev** [comment]
I do not think conflicts are solvable here. The code changed significantly, and one needs to rewrite it from scratch. @casz also said that you @timja have already started working on it, so I did not really plan working on it :)

I reopened this PR mostly for the sake for visibility, because some of the code splitting approaches can be still reqused

**Pull request closed without merging**
