### PR TITLE
Suggest user to install configuration-as-code-support if not installed

### PR DESCRIPTION
**Pull request by MadsNielsen**
Right, after having a couple of talks with collegaues, i think it would make sense to inform the users of possible solutions, if said user forgot to include the support plugin, which is almost required at this point for minimal functionality. 

WDYT? Should we include suggestions in exception to help users? Let me know. Close this if it has no interest.

### CODE REVIEW

**Comment by jonbrohauge** [comment]
Why not make it obligatory to have the -support plugin installed as well (read: dependency)?

**Comment by MadsNielsen** [comment]
@jonbrohauge That would create a cyclic dependency, the support plugin depends on casc to run it's test for integration

**Comment by jonbrohauge** [comment]
ok.. that sucks...
But I still don't get it why it has been split up into two parts.
Maybe I'm just daft...

**Comment by MadsNielsen** [comment]
Build is failing because....connection issue?

**Comment by casz** [comment]
rebase commit and push to trigger ci? 😅

**Comment by MadsNielsen** [comment]
Yep...that fixed it :)

**Pull request merged**
