### PR TITLE
Cleanup references to support plugin after removal

### PR DESCRIPTION
**Pull request by timja**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!

- [x] Please describe what you did

- [na] Link to relevant GitHub issues or pull requests

- [na] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org)

- [na] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### Description

Stop nagging me to install the support plugin!

### CODE REVIEW

**Comment by casz** [comment]
@timja I added some more cleanup :sweat_smile:

**Comment by timja** [comment]
thanks 👍

**Comment by casz** [comment]
Doing it here since gitter doesn't support threading :cry: 
@oleg-nenashev regarding deprecation: the support plugin never had a URL for the wiki in it's POM: https://github.com/jenkinsci/configuration-as-code-plugin/blob/configuration-as-code-1.18/support/pom.xml

Would you mind if we did a sneaky deploy of configuration-as-code-support adding the URL? Either by adding the URL to 1.18 in artifactory or deploying 1.19 with the URL?

**Comment by casz** [comment]
I tried adding https://wiki.jenkins.io/display/JENKINS/Configuration+as+Code+Support+Plugin but of course, the magic happens inside pom.xml

I think we need a better way of marking plugins deprecated either through repo.jenkins-ci.org as artifactory supports adding parameters to an already released package. Or controlled through a git repo much like [ignoring them from update-center](https://github.com/jenkins-infra/update-center2/blob/master/src/main/resources/artifact-ignores.properties).
Would be great if we had a similar file for artifact deprecated :sweat_smile: 

cc @daniel-beck

**Comment by oleg-nenashev** [comment]
FTR  https://wiki.jenkins.io/display/JENKINS/Deprecating+a+Plugin

**Comment by casz** [comment]
@oleg-nenashev following that I currently cannot mark the plugin deprecated as noted by my comments above :sweat:

**Comment by oleg-nenashev** [comment]
I know. I just link the process description.
I don't remember when I followed this process last time, eons ago

**Comment by casz** [comment]
I think I managed to use `mvn deploy` for only the support plugin: https://repo.jenkins-ci.org/webapp/#/artifacts/browse/tree/PomView/releases/io/jenkins/configuration-as-code/configuration-as-code-support/1.19/configuration-as-code-support-1.19.pom

**Comment by daniel-beck** [comment]
AFAIUI, https://wiki.jenkins.io/display/JENKINS/Deprecating+a+Plugin is wrong, we don't care about wiki labels anymore outside the wiki (i.e. in update site generation).

**Comment by timja** [comment]
So do we just add it here?
https://github.com/jenkins-infra/update-center2/blob/master/src/main/resources/artifact-ignores.properties

**Comment by daniel-beck** [comment]
This is where you prevent a plugin or specific release from being published on the update center and plugins.jenkins.io. If that's what you want to do, that's the way to do it.

**Comment by casz** [comment]
Perhaps the docs should be updated to include deprecation? Or do we perhaps in the new plugin management tool/cli want to introduce a way to deprecate a plugin?

**Comment by daniel-beck** [comment]
What does it mean to "deprecate" a plugin? Seems everyone has their own definition. Would you consider https://plugins.jenkins.io/multi-branch-project-plugin deprecated?

I think this discussion should be had elsewhere. If you want to _stop distributing_ the plugin, that's done as described in the docs I link to, with no alternative.

**Pull request merged**
