### PR TITLE
Allow multiple YAML sources to be specified

### PR DESCRIPTION
**Pull request by basil**
After all these years, we're finally getting around to setting up JCasC on our Jenkins controllers. For a variety of reasons, we'd like to use URLs rather than files/directories to configure our controllers. But we also want to be able to define a primary YAML file with base configuration that applies to all controllers and a secondary YAML file with controller-specific configuration that is unique to each controller. But in the current system, you can only specify a single URL in the YAML source (e.g., `CASC_JENKINS_CONFIG`, `-Dcasc.jenkins.config`, or the text box in the UI's "replace" page) . Wanting to use two YAML files currently seems to preclude one from using a URL as the YAML source.

This PR attempts to solve the problem by allowing the YAML source (e.g., `CASC_JENKINS_CONFIG`, `-Dcasc.jenkins.config`, or the text box in the UI's "replace" page) to be a whitespace-separated list of URLs/files/directories rather than a single URL/file/directory. This preserves compatibility with the existing semantics while also allowing the user to use multiple URLs for multiple YAML files.

I have only done some basic manual testing so far, but if the maintainers are receptive to this PR I will add some automated tests and documentation.

### CODE REVIEW

**Comment by timja** [comment]
Concept is fine, docs + test required and can you check what the UI looks like? May need to fiddle with it to make multiple URLs look nice

**Review by jetersen — CHANGES_REQUESTED** [review]
This looks promising 😅

**Comment by basil** [comment]
@timja I added tests and updated the documentation to cover this new functionality. I also checked the UI. While there is still a single textbox for input entry, I think this makes sense as it is consistent with the single environment variable `CASC_JENKINS_CONFIG` or the single Java property `-Dcasc.jenkins.config`. I verified that when the configuration is replaced with multiple files, the multiple files display nicely in the UI as two separate bullet points in a bulleted list.

@jetersen I replaced the space-separated list with a comma-separated list. This should address your feedback about spaces in the path.

**Review by timja — APPROVED** [review]

**Review by jetersen — APPROVED** [review]

**Comment by basil** [comment]
Thanks for the quick review and release!

**Pull request merged**
