### PR TITLE
Use a cache to resolve configurators

### PR DESCRIPTION
**Pull request by ndeloof**
will avoid running same lookup for each and every comparable type. 
Especially considering we want to run check before and configuration is applied

### CODE REVIEW

**Comment by ndeloof** [comment]
I actually wonder if we should move all the `lookup` methods into a `ConfiguratorRegistry` or something comparable that would be such an extension. This would be part of the ConfigurationContext, so easier to tweak/override for use in another context. wdyt @oleg-nenashev  ?

**Comment by oleg-nenashev** [comment]
> This would be part of the ConfigurationContext, so easier to tweak/override for use in another context. wdyt @oleg-nenashev ?

Looks good to me, but we will need some developer documentation to show examples

**Comment by ndeloof** [comment]
made a more significant change here:
`ConfiguratorRegistry` encapsulate the `lookup` (and cache) logic
`ConfiguratorContext` allows to use a consistent set of configurator resources during the whole process.

**Comment by ndeloof** [comment]
we clearly need some developer documentation, see https://github.com/jenkinsci/configuration-as-code-plugin/issues/315

**Pull request merged**
