### PR TITLE
FEAT: add pipeline build step for CasC plugin.

### PR DESCRIPTION
**Pull request by dgarzon**
This PR is meant to address https://github.com/jenkinsci/configuration-as-code-plugin/issues/659. It can be considered a WIP, but the simple functionality is tested.

### CODE REVIEW

**Comment by ewelinawilkosz** [comment]
nice feature @dgarzon, it's taking some time to review all PRs but it's not being ignored!

**Comment by timja** [comment]
Is this safe, permissions wise?

**Comment by dgarzon** [comment]
@timja @ewelinawilkosz I don't know the answer to that! What do you think would make it safe? I would like to get this merged, and can do the work needed.

**Comment by timja** [comment]
Looking at this again, I think a reload may be safe but I don’t think you should be able to override the global configuration with the targets as that could allow any user to reconfigure your Jenkins

**Comment by ndeloof** [comment]
@timja is right that such a build step *need* to check the pipeline is ran by an administrator.

**Comment by casz** [comment]
Could you resolve conflicts and add the check for Jenkins administrator permission, thank @dgarzon

**Comment by imod** [comment]
is anyone still working on this? I think this would be a key feature of CasC and will finally allow continuous controlled configuration changes. e.g. for credentials

**Comment by casz** [comment]
Feel free to reopen the PR 😁

**Comment by timja** [comment]
This usecase was mostly solved with:
https://github.com/jenkinsci/configuration-as-code-plugin/pull/712

**Comment by casz** [comment]
@dgarzon @imod closing this as stated by @timja it can be soled by #712 if you disagree feel free to reopen/resend PR 😅

**Pull request closed without merging**
