### PR TITLE
Support (global) node properties, including environment variables

### LINKED ISSUE #173: Global environment variables can't be set
Currently it is either not possible or not clear enough how to set up global environment variables
pretty important part!

### PR DESCRIPTION
**Pull request by ndeloof**
fix #173 
supported syntax :
```
jenkins:
  nodeProperties:
    - envVars:
        env:
          - key: FOO
            value: BAR
```

### CODE REVIEW

**Comment by ewelinawilkosz** [comment]
Nice! thanks,
I will make update in demos folder

**Comment by antgel** [comment]
@ndeloof @ewelinawilkosz Does this feature support use of interpolated environment variables within the .yaml? For example, let's say I have Jenkins on three different environments, but I don't want to maintain three separate .yaml configs because they're all the same apart from region and environment, which are in operating system environment variables via Puppet and just need to be inserted here and there.

**Comment by ndeloof** [comment]
@antgel yes. A quick test would had told you :)

**Comment by antgel** [comment]
@ndeloof Sorry, how can I test it? Is the syntax documented somewhere? Apologies if this is obvious.

**Comment by antgel** [comment]
@ndeloof Ping? For clarity, say, I have an environment variable `REGION` which I want to use in the .yaml as part of a URL. Is that use case supported and if so, what's the syntax? All I see in the examples is the ability to *set* environmental variables in the .yaml.

**Comment by ndeloof** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin#handling-secrets

**Comment by antgel** [comment]
@ndeloof Thanks, can't believe I missed it. Probably when I was skimming the docs, I didn't immediately associate variables with "secrets".

**Pull request merged**
