### PR TITLE
Validate LDAP demo with the integrations tests

### PR DESCRIPTION
**Pull request by v1v**
As a consequence of https://github.com/jenkinsci/configuration-as-code-plugin/pull/1055 let's move each demos in independent PRs to track all the required dependencies.

`integrations/src/test/resources/io/jenkins/plugins/casc/LDAPSecurityRealmTest.yml` has been deleted since it's already tested with the demos.

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Comment by casz** [comment]
I believe it would be good to demo both ldap config with regular openLDAP and Active Directory LDAP integration

**Comment by v1v** [comment]
The LDAP/AD plugins for jenkins run some tests for such an environment:
- https://github.com/jenkinsci/ldap-plugin/blob/master/src/test/java/hudson/security/docker/PlanetExpressTest.java
- https://github.com/jenkinsci/active-directory-plugin/blob/master/src/test/java/hudson/plugins/active_directory/docker/TheFlintstonesTest.java

I'm not sure about your suggestion, so let me ask:
- do you mean to add further test scenarios within this PR? 
- Or something to work in another follow-up? 

In both cases, I'm not sure what we are trying to achieve though. IIUC, the plugins should be the ones to provide the ITs for those scenarios, or do you mean to provide a more realistic setup to be used within the JCasC for helping purposes, no for testing (although it might happen anyway)?

**Comment by casz** [comment]
I was asking for demo config being tested for both active directory plugin and ldap plugin

**Comment by casz** [comment]
I guess I already forgot about #1055

**Pull request merged**
