### PR TITLE
Added support for config-file-provider plugin (# 476)

### PR DESCRIPTION
**Pull request by srempfer**
#476 

@ndeloof: I'm new in Jenkins plugin contribution, so please let me know what do think about the code. 
Regrads Stefan

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
IMHO the fix should be done on the Config File Provider Plugin side. JCasC is in the RC state, so nothing blocks from making fixes in plugins directly

**Comment by ndeloof** [comment]
I agree with @oleg-nenashev that this should be proposed as an optional extension to config-file-provider, as we would like to move all custom configurators to target plugins. Also, doing so you can introduce in `GlobalConfigFiles` the missing `setConfigs` setter that make it required to implement custom code, and will just need to declare a RootConfigurator.

**Comment by srempfer** [comment]
Just created a JIRA ticket (JENKINS-53247) - will try to do the compatibility changes there

**Comment by HerrmannHinz** [comment]
yay! super! just in time =)

**Comment by ndeloof** [comment]
closing this with preference to a PR on config-file-provider plugin

**Pull request closed without merging**
