### PR TITLE
Issue #29 - Allow configuring Slave2MasterSecurity within Jenkins settings

### LINKED ISSUE #29: Ability to express "Enable Agent → Master Access Control" in configuration
Hi,

I've tried to express that with the current version without success:
```groovy
import jenkins.security.s2m.AdminWhitelistRule
import jenkins.model.Jenkins

Jenkins.instance.injector.getInstance(AdminWhitelistRule).masterKillSwitch = false
```

I believe it will have to be some glue code here.

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Fixes #29. I used some hacks in order to bind `AdminWhitelistRule ` into the Jenkins configuration section. Sanity check is required before I proceed with other controls.

```yaml
jenkins:
  remotingSecurity:
    enabled: true
```

@reviewbybees @ndeloof @ewelinawilkosz

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
> I'm looking for a way to group all security options under top level security item in yaml, like we do for Descriptors in security category. Would need to find some way to move this one there

I can rework it, not a big deal

**Comment by oleg-nenashev** [comment]
If you offer a "security" top level item, in this PR you just need to move one like from JenkinsConfigurator to another configurator

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by ndeloof** [comment]
> If you offer a "security" top level item, in this PR you just need to move one like from JenkinsConfigurator to another top-level-configurator

yes, the pain point is this top level yaml node is here to match all Descriptors within "security" category, so will need to find some way to add extra attributes to such a pseudo-node. I anyway have the same issue trying to move `GlobalSecurityConfiguration` on this same section.

**Comment by casz** [comment]
`jenkins    | WARNING: Ignoring attribute remotingSecurity for Jenkins instance. No setter` 😭

**Comment by oleg-nenashev** [comment]
Inverted value is definitely a bug. Will check

**Pull request merged**
