### PR TITLE
Fix role strategy export

### PR DESCRIPTION
**Pull request by timja**
### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!

- [x] Please describe what you did

- [x] Link to relevant GitHub issues or pull requests
Fixes https://github.com/jenkinsci/configuration-as-code-plugin/issues/534

- [na] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org)

- [x] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### Description

Fixes role strategy exporting

### CODE REVIEW

**Comment by casz** [comment]
I would prefer it to be moved rather than maintain it here.
Please apply the nessary fix here in JCasC and sent the update to role strategy plugin

**Comment by casz** [comment]
This should be a upstream fix to the downstream fix in role strategy plugin

**Comment by timja** [comment]
I need an incrementals version for that 👅 
and the builds failing on the other side.

Obviously will remove the code from here as soon as we can figure out what's wrong on the tests in role strategy.

I just wanted to fix it up so that I could get a passing test.

**Comment by casz** [comment]
You should have a incremental already 🤔

**Comment by timja** [comment]
🤦‍♂ 
https://github.com/casz/role-strategy-plugin/pull/1

**Comment by casz** [comment]
Just testing whether the snapshot works as well :sweat:

**Comment by timja** [comment]
@casz you good with this or do you want the role strategy changes backed out?

**Pull request merged**
