### PR TITLE
slaveAttributes option added

### PR DESCRIPTION
**Pull request by ewelinawilkosz**
@gbastkowski I'm updating mesos demo with attribute you've figured out
before I merge, is there anything else regarding mesos that you miss or we miss in demo file?

### CODE REVIEW

**Comment by gbastkowski** [comment]
There is quite a few properties, hidden behind _Advanced_ buttons in Jenkins' UI.
But the _slaveAttributes_ is IMHO the only one that's non-trivial to figure out.

**Comment by ewelinawilkosz** [comment]
thanks for figuring out then!

**Comment by oleg-nenashev** [comment]
Oh well. Could somebody create a follow-up ticket for cleaning up "slave.*" references?

**Comment by oleg-nenashev** [comment]
@ewelinawilkosz does the CasC plugin already have a JIRA component created?

**Comment by ewelinawilkosz** [comment]
no, can we come back to JIRA case at the meeting on Monday?

**Comment by oleg-nenashev** [comment]
sure

**Pull request merged**
