### PR TITLE
1.0 released, API is not Beta anymore

### PR DESCRIPTION
**Pull request by ndeloof**

### CODE REVIEW

**Comment by ndeloof** [comment]
This will allow to move custom Configurators out from support module to target plugin, without requirement for them to enable Beta annotation support
(also prevent weird classloading issue using hpi:run and third party plugin test suites)

**Comment by oleg-nenashev** [comment]
I would prefer to keep it for a while so that we get more feedback.
But it is generally up to you and @ewelinawilkosz , @ndeloof

**Comment by ewelinawilkosz** [comment]
I'm not strictly against, but I expect to release a number of 1.X with fixes we introduce constantly in upcoming weeks - 1.1 (?) is coming this week, so if @oleg-nenashev believes we can get some feedback will you both be ok with waiting till 1.2?

**Comment by ndeloof** [comment]
Beta annotation is not just breaking hpi:run, it also prevent test-cases to run successfully for third party plugins

**Pull request merged**
