### PR TITLE
safe way to scan for configs

### PR DESCRIPTION
**Pull request by lanwen**
This commit adds resource control for all files, as previously the
stream close was neglected which may lead to resource leaks.

This commit uses stream api to search configs and run reconfiguration.
The stream api here allows to reduce code complexity as we get
flat flow of paths, that converted to entries in config and then
processed by configurators.

In case of files search stream api gives us one line to get the flat
stream of paths - it allows us to pay more attention to error handling

Passing InputStreams by reference between method without error handling
usually looks like antipattern, so all the file logic is concentrated
inside of dedicated methods.

### CODE REVIEW

**Comment by MadsNielsen** [comment]
@lanwen Could you take a look and see if you could incorporate these change(s) in: https://github.com/jenkinsci/configuration-as-code-plugin/pull/120 instead?

Basically im trying to extract the config-parsing to an extension point, and the most generic return type a config parser i could think of was the input stream...but if you've got a better idea on something that works for other stuff than flat files im ok with that.

**Comment by MadsNielsen** [comment]
Looks good to me, doesn't break anything I'll be taking another stab at #120 after this merge.

**Comment by lanwen** [comment]
Thanks!

**Comment by MadsNielsen** [comment]
np @lanwen i'd appreciate your help on #120 after this, i'll be following your advice and making the config sources as generic as possible by returning a Map of <String,Object>. Im thinking of splitting the ConfigSources into two categories, Static ones like file paths and urls pointing to yaml files (I'll extend your solution to work with URI's as well), and the dynamic sources like Push for git repos pull requests etc... 

For this first iteration we'll go with the focus on the static ones. 

It's taking me some time to wrap my head around the Stream api for this pull request, which makes it more exciting... :-)

**Pull request merged**
