### PR TITLE
Revert "Replace Guava's cache with Caffeine."

### PR DESCRIPTION
**Pull request by jtnord**
This reverts commit 290e5ddf4e36b8d727ef5989f27ee5cf2aef13a1.

### Your checklist for this pull request

🚨 Please review the [guidelines for contributing](../blob/master/docs/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or in [Jenkins JIRA](https://issues.jenkins-ci.org)
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Did you provide a test-case? That demonstrates feature works or fixes the issue.

### CODE REVIEW

**Review by jglick — APPROVED** [review]
Fine for a hotfix.

**Comment by jetersen** [comment]
🤷‍♂️ Simply skip v1.48 why spend time reverting it?

**Comment by jtnord** [comment]
> 🤷‍♂️ Simply skip v1.48 why spend time reverting it? as this was only thing that was added to JCASC plugin in v1.48.

yeah that was my choice as well.  I filed this so that others can make that decision.  It is close to a long weekend for me - so unlikely to get to the root cause before more people hit the issue.

**Comment by jglick** [comment]
This PR just reverts the Caffeine change, while leaving the other Guava removals which are likely not problematic, so it seems a bit cleaner.

**Pull request merged**
